language: ruby

rvm:
  - 1.9.3
  - 2.1
 

gemfile:
  - Gemfile
  - gemfiles/activerecord31.gemfile
  
script: bundle exec rake test

before_script:
  - mysql -e 'create database groupdate_test;'
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - psql -c 'create database groupdate_test;' -U postgres


#build_image: shippable/minv2:beta

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    
