language: ruby



rvm:
  - 2.1
  
script: bundle exec rake test

before_script:
  - mysql -e 'create database groupdate_test;'
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - psql -c 'create database groupdate_test;' -U postgres


#build_image: shippable/minv2:beta

matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/activerecord31.gemfile
